# Generated by Django 5.2.4 on 2025-07-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='sensors',
            field=models.ManyToManyField(blank=True, related_name='stations', to='sensors.sensor'),
        ),
    ]
