# Generated by Django 5.2.4 on 2025-07-30 22:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'Temperature'), (2, 'Humidity'), (3, 'Wind'), (4, 'Rainfall'), (5, 'Solar Radiation')])),
                ('unit', models.IntegerField(choices=[(1, 'Graus Celsius (°C) (Celsius)'), (3, 'Porcentagem (%) (Percent)'), (4, 'Metros por Segundo (m/s) (Meters per Second)'), (7, 'Milímetros (mm) (Millimeters)'), (9, 'Watts por Metro Quadrado (W/m²) (Watts per Meter Squared)')])),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
